apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openldap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- if .Values.envFrom }}
          envFrom:
          {{- with .Values.envFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
          ports:
            - name: ldap-tcp
              containerPort: 389
              protocol: TCP
            - name: ldap-udp
              containerPort: 389
              protocol: UDP
            - name: ldaps-tcp
              containerPort: 636
              protocol: TCP
            - name: ldaps-udp
              containerPort: 636
              protocol: UDP
          volumeMounts:
          - name: {{ .Release.Name }}-config
            mountPath: '/etc/openldap/slapd.d'
          - name: {{ .Release.Name }}-database
            mountPath: '/var/lib/ldap'
          livenessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Release.Name }}-config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
      - name: {{ .Release.Name }}-database
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-database
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
