apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $name, $content := .Values.service.ports }}
  {{- if .enabled }}
    - port: {{ $content.port }}
      targetPort: {{ $content.targetPort }}
      protocol: {{ $content.protocol }}
      name: {{ $name }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
